---

- name: read variables for zone {{ _aws_route53_zone }}
  include_vars:
    host_vars/{{ inventory_hostname }}/route53/{{ _aws_route53_zone }}.yml

- name: create zone {{ _aws_route53_zone }}
  route53_zone:
    zone: '{{ _aws_route53_zone }}'
    comment: '{{ aws_route53_zone.comment | default(omit) }}'
    state: present
    profile: '{{ aws_profile }}'

- name: create zone records
  route53:
    zone:      '{{ _aws_route53_zone }}'
    profile:   '{{ aws_profile }}'
    command:   create
    overwrite: True

    record:  '{{ ("" if item.name == "@" else item.name + ".") +
                 _aws_route53_zone }}'
    ttl:     '{{ item.ttl | default(omit) }}'
    type:    '{{ item.type }}'

    value: >-
      {{ (item.alias_target + ".")
         if "alias_target" in item
         else item.value }}

    alias:   '{{ True
                 if "alias_target" in item
                 else False
                 | default(omit) }}'

    alias_hosted_zone_id: >-
      {{ aws_s3_website_endpoint_route53_hosted_zone_ids[item.alias_target]
         if "alias_target" in item
         else None
         | default(omit) }}

  with_items: '{{ aws_route53_zone.records }}'
